apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  DB_HOST: "db-service"
  DB_NAME: "postgres"
  DB_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password"
